/* The following code was generated by JFlex 1.4.3 on 20/11/24, 18:54 */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 20/11/24, 18:54 from the specification file
 * <tt>C:/Users/THINKPAD/OneDrive/Documentos/1 ISIC/5 Semestre/Lenguajes y Automatas1/Unidad IV/AnalizadorLexico/AnalizadorLexico/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\16\2\0\1\3\22\0\1\3\1\42\1\64\1\70"+
    "\1\57\1\22\1\40\1\65\1\45\1\47\1\21\1\17\1\3\1\20"+
    "\1\63\1\15\12\2\1\46\1\56\1\37\1\31\1\32\2\0\1\44"+
    "\1\53\1\54\1\73\1\51\1\52\2\44\1\76\2\44\1\77\1\44"+
    "\1\35\1\44\1\33\1\44\1\24\3\44\1\74\4\44\1\61\1\66"+
    "\1\62\1\23\1\1\1\0\1\27\1\75\1\25\1\30\1\10\1\7"+
    "\1\36\1\14\1\4\2\43\1\11\1\71\1\5\1\34\1\72\1\43"+
    "\1\55\1\12\1\6\1\26\1\43\1\13\3\43\1\60\1\41\1\50"+
    "\43\0\1\67\uff5e\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\7\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\5\1\1\1\15"+
    "\2\14\1\16\1\17\1\20\1\21\1\14\1\22\1\23"+
    "\1\24\1\25\4\14\1\1\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\37\2\5\4\14"+
    "\1\40\1\41\1\40\1\42\2\40\1\43\4\40\1\4"+
    "\1\44\1\45\3\40\1\46\1\47\1\0\1\50\1\40"+
    "\1\51\1\40\1\0\1\52\1\0\1\53\1\0\1\54"+
    "\1\0\6\40\1\0\1\55\1\0\1\56\21\40\1\57"+
    "\1\60\1\61\1\62\1\0\1\63\1\64\1\65\1\40"+
    "\1\66\1\40\1\67\2\40\1\70\1\0\10\40\1\71"+
    "\5\40\1\72\1\41\1\73\1\40\1\74\1\40\1\0"+
    "\7\40\1\75\1\40\1\76\1\77\1\100\1\101\1\102"+
    "\1\103\1\40\1\104\20\40\1\105\3\40\1\106\5\40"+
    "\1\107\1\40\1\110\1\40\1\111\1\112\1\113\5\40"+
    "\1\114\2\40\1\115";

  private static int [] zzUnpackAction() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\100\0\200\0\300\0\u0100\0\u0140\0\200\0\u0180"+
    "\0\u01c0\0\u0200\0\u0240\0\u0280\0\u02c0\0\u0300\0\u0340\0\100"+
    "\0\100\0\100\0\u0380\0\u03c0\0\u0400\0\u0440\0\u0480\0\u04c0"+
    "\0\u0500\0\100\0\100\0\100\0\200\0\u0540\0\u0580\0\100"+
    "\0\u05c0\0\u0600\0\u0640\0\u0680\0\u06c0\0\u0700\0\u0740\0\100"+
    "\0\u0780\0\100\0\u07c0\0\100\0\100\0\100\0\100\0\100"+
    "\0\u0800\0\u0840\0\u0880\0\u08c0\0\u0900\0\u0940\0\200\0\300"+
    "\0\u0980\0\200\0\u09c0\0\u0a00\0\u0a40\0\u0a80\0\u0ac0\0\u0b00"+
    "\0\u0b40\0\u0b80\0\100\0\100\0\u0bc0\0\u0c00\0\u0c40\0\100"+
    "\0\100\0\u0c80\0\100\0\u0cc0\0\200\0\u0d00\0\u0d40\0\100"+
    "\0\u0d80\0\100\0\u0dc0\0\100\0\u0e00\0\u0e40\0\u0e80\0\u0ec0"+
    "\0\u0f00\0\u0f40\0\u0f80\0\u0fc0\0\100\0\u1000\0\100\0\u1040"+
    "\0\u1080\0\u10c0\0\u1100\0\u1140\0\u1180\0\u11c0\0\u1200\0\u1240"+
    "\0\u1280\0\u12c0\0\u1300\0\u1340\0\u1380\0\u13c0\0\u1400\0\u1440"+
    "\0\100\0\200\0\200\0\100\0\u1480\0\100\0\100\0\200"+
    "\0\u14c0\0\200\0\u1500\0\200\0\u1540\0\u1580\0\100\0\u15c0"+
    "\0\u1600\0\u1640\0\u1680\0\u16c0\0\u1700\0\u1740\0\u1780\0\u17c0"+
    "\0\200\0\u1800\0\u1840\0\u1880\0\u18c0\0\u1900\0\200\0\100"+
    "\0\200\0\u1940\0\200\0\u1980\0\u19c0\0\u1a00\0\u1a40\0\u1a80"+
    "\0\u1ac0\0\u1b00\0\u1b40\0\u1b80\0\200\0\u1bc0\0\200\0\200"+
    "\0\200\0\200\0\200\0\200\0\u1c00\0\100\0\u1c40\0\u1c80"+
    "\0\u1cc0\0\u1d00\0\u1d40\0\u1d80\0\u1dc0\0\u1e00\0\u1e40\0\u1e80"+
    "\0\u1ec0\0\u1f00\0\u1f40\0\u1f80\0\u1fc0\0\u2000\0\200\0\u2040"+
    "\0\u2080\0\u20c0\0\200\0\u2100\0\u2140\0\u2180\0\u21c0\0\u2200"+
    "\0\200\0\u2240\0\200\0\u2280\0\200\0\200\0\200\0\u22c0"+
    "\0\u2300\0\u2340\0\u2380\0\u23c0\0\200\0\u2400\0\u2440\0\200";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\2\7\1\10\1\11"+
    "\1\7\1\12\1\13\1\14\1\15\1\5\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\3\7\1\25\1\26"+
    "\1\27\1\7\1\30\1\7\1\31\1\32\1\33\1\34"+
    "\1\7\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\7\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\62"+
    "\1\63\1\64\1\7\1\65\1\66\101\0\2\67\1\0"+
    "\11\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\2\0\1\70\100\0\1\5\12\0"+
    "\1\5\62\0\2\67\1\0\1\67\1\71\1\67\1\72"+
    "\5\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\11\67\7\0"+
    "\2\67\1\73\2\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\5\67\1\74"+
    "\3\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\1\75\3\67"+
    "\1\76\4\67\7\0\3\67\1\77\1\67\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\1\0\2\67"+
    "\1\0\10\67\1\100\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\3\67\1\101\1\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\15\0\1\102\101\0"+
    "\1\103\100\0\1\104\60\0\2\67\1\0\11\67\7\0"+
    "\1\67\1\105\3\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\1\106\10\67"+
    "\7\0\3\67\1\107\1\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\31\0\1\110\1\111\76\0"+
    "\1\112\1\113\46\0\2\67\1\0\11\67\7\0\5\67"+
    "\2\0\1\67\1\114\2\67\4\0\2\67\4\0\5\67"+
    "\13\0\5\67\1\115\1\67\1\0\2\67\1\0\4\67"+
    "\1\116\4\67\7\0\5\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\31\0\1\117\5\0\1\120"+
    "\60\0\1\121\25\0\1\122\51\0\1\123\26\0\1\124"+
    "\61\0\1\125\47\0\2\67\1\0\1\67\1\126\7\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\5\67\1\127\3\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\5\67"+
    "\2\0\1\67\1\130\2\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\5\67\1\131\3\67"+
    "\7\0\3\67\1\132\1\67\2\0\1\67\1\133\2\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\20\0\1\134"+
    "\70\0\1\135\150\0\1\136\100\0\1\137\15\0\2\67"+
    "\1\0\1\140\10\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\4\67\1\141\13\0\7\67\1\0\2\67\1\0\4\67"+
    "\1\142\4\67\7\0\5\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\11\67"+
    "\7\0\3\67\1\143\1\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\1\67"+
    "\1\144\7\67\7\0\5\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\1\145\6\67\1\0\2\67\1\0"+
    "\4\67\1\146\4\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\2\67\1\72\6\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\1\67\1\147\7\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\6\67\1\150\2\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\5\67\2\0\2\67\1\151\1\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\5\67\2\0\3\67\1\152\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\5\67"+
    "\1\153\3\67\7\0\5\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\1\154"+
    "\10\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\11\67\7\0"+
    "\1\67\1\155\3\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\16\102\1\0\61\102\1\0\2\67"+
    "\1\0\11\67\7\0\2\67\1\156\2\67\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\1\0\2\67"+
    "\1\0\11\67\7\0\1\67\1\157\3\67\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\1\0\2\67"+
    "\1\0\6\67\1\160\2\67\7\0\5\67\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\37\0\1\161"+
    "\41\0\2\67\1\0\6\67\1\162\2\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\1\0\2\67\1\0\11\67\7\0\5\67\2\0\3\67"+
    "\1\163\4\0\2\67\4\0\5\67\13\0\7\67\32\0"+
    "\1\164\47\0\1\165\143\0\1\166\100\0\1\167\31\0"+
    "\2\67\1\0\2\67\1\170\6\67\7\0\5\67\2\0"+
    "\4\67\4\0\2\67\4\0\5\67\13\0\7\67\1\0"+
    "\2\67\1\0\11\67\7\0\5\67\2\0\1\67\1\171"+
    "\2\67\4\0\2\67\4\0\5\67\13\0\7\67\1\0"+
    "\2\67\1\0\11\67\7\0\5\67\2\0\1\67\1\172"+
    "\2\67\4\0\2\67\4\0\5\67\13\0\7\67\1\0"+
    "\2\67\1\0\11\67\7\0\3\67\1\173\1\67\2\0"+
    "\4\67\4\0\2\67\4\0\5\67\13\0\7\67\1\0"+
    "\2\67\1\0\11\67\7\0\4\67\1\174\2\0\4\67"+
    "\4\0\2\67\4\0\4\67\1\175\13\0\7\67\1\0"+
    "\2\67\1\0\1\67\1\176\7\67\7\0\5\67\2\0"+
    "\4\67\4\0\2\67\4\0\5\67\13\0\7\67\56\0"+
    "\1\177\41\0\1\200\60\0\2\67\1\0\4\67\1\201"+
    "\4\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\4\67\1\202"+
    "\4\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\2\67\1\203"+
    "\6\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\11\67\7\0"+
    "\5\67\2\0\4\67\4\0\2\67\4\0\4\67\1\204"+
    "\13\0\7\67\1\0\2\67\1\0\2\67\1\205\6\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\5\67\13\0\1\67"+
    "\1\206\5\67\1\0\2\67\1\0\4\67\1\207\4\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\1\67"+
    "\1\210\3\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\4\67\1\72\4\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\5\67"+
    "\2\0\1\67\1\211\2\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\2\67"+
    "\1\212\2\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\1\213\10\67\7\0"+
    "\5\67\2\0\4\67\4\0\2\67\4\0\5\67\13\0"+
    "\7\67\1\0\2\67\1\0\5\67\1\150\3\67\7\0"+
    "\5\67\2\0\4\67\4\0\2\67\4\0\5\67\13\0"+
    "\7\67\1\0\2\67\1\0\4\67\1\214\4\67\7\0"+
    "\5\67\2\0\4\67\4\0\2\67\4\0\5\67\13\0"+
    "\7\67\1\0\2\67\1\0\11\67\7\0\3\67\1\215"+
    "\1\67\2\0\4\67\4\0\2\67\4\0\5\67\13\0"+
    "\7\67\1\0\2\67\1\0\5\67\1\216\3\67\7\0"+
    "\5\67\2\0\4\67\4\0\2\67\4\0\5\67\13\0"+
    "\7\67\1\0\2\67\1\0\11\67\7\0\5\67\2\0"+
    "\1\67\1\217\2\67\4\0\2\67\4\0\5\67\13\0"+
    "\7\67\2\0\1\165\44\0\1\220\31\0\2\67\1\0"+
    "\2\67\1\221\6\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\6\67\1\222\2\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\6\67\1\223\2\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\6\67\1\224\2\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\61\0\1\225\17\0"+
    "\2\67\1\0\1\67\1\226\7\67\7\0\5\67\2\0"+
    "\4\67\4\0\2\67\4\0\5\67\13\0\7\67\1\0"+
    "\2\67\1\0\11\67\7\0\4\67\1\227\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\1\0\2\67"+
    "\1\0\4\67\1\230\4\67\7\0\5\67\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\1\0\2\67"+
    "\1\0\1\231\10\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\4\67\1\232\13\0\7\67\1\0\2\67\1\0\11\67"+
    "\7\0\5\67\2\0\1\67\1\233\2\67\4\0\2\67"+
    "\4\0\4\67\1\234\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\4\67\1\235\13\0\7\67\1\0\2\67\1\0\1\236"+
    "\10\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\1\67\1\237"+
    "\7\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\11\67\7\0"+
    "\5\67\2\0\4\67\4\0\2\67\4\0\4\67\1\240"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\4\67\1\241\13\0"+
    "\7\67\1\0\2\67\1\0\11\67\7\0\4\67\1\242"+
    "\2\0\4\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\1\0\2\67\1\0\11\67\7\0\5\67\2\0\1\67"+
    "\1\243\2\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\1\0\2\67\1\0\4\67\1\244\4\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\1\0\2\67\1\0\2\67\1\245\6\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\62\0\1\246\16\0\2\67\1\0\2\67\1\247\6\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\4\67\1\250\4\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\1\67\1\251\7\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\3\67"+
    "\1\252\1\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\5\67"+
    "\2\0\1\67\1\253\2\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\4\67\1\254\13\0"+
    "\7\67\1\0\2\67\1\0\1\255\10\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\1\0\2\67\1\0\11\67\7\0\5\67\2\0\1\67"+
    "\1\256\2\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\1\0\2\67\1\0\11\67\7\0\3\67\1\257\1\67"+
    "\2\0\4\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\1\0\2\67\1\0\11\67\7\0\5\67\2\0\4\67"+
    "\4\0\2\67\4\0\4\67\1\260\13\0\7\67\1\0"+
    "\2\67\1\0\2\67\1\261\6\67\7\0\5\67\2\0"+
    "\4\67\4\0\2\67\4\0\5\67\13\0\7\67\1\0"+
    "\2\67\1\0\4\67\1\262\4\67\7\0\5\67\2\0"+
    "\4\67\4\0\2\67\4\0\5\67\13\0\7\67\1\0"+
    "\2\67\1\0\11\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\4\67\1\263\2\67\1\0"+
    "\2\67\1\0\11\67\7\0\4\67\1\264\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\1\0\2\67"+
    "\1\0\2\67\1\265\6\67\7\0\5\67\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\1\0\2\67"+
    "\1\0\11\67\7\0\5\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\1\266\6\67\1\0\2\67\1\0"+
    "\1\67\1\267\7\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\1\67\1\270\7\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\3\67\1\271\1\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\4\67\1\272\4\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\4\67\1\273\13\0\7\67\1\0\2\67\1\0\5\67"+
    "\1\274\3\67\7\0\5\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\11\67"+
    "\7\0\2\67\1\275\2\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\11\67"+
    "\7\0\3\67\1\276\1\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\1\277"+
    "\10\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\2\67\1\300"+
    "\6\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\6\67\1\301"+
    "\2\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\11\67\7\0"+
    "\5\67\2\0\4\67\4\0\2\67\4\0\4\67\1\302"+
    "\13\0\7\67\1\0\2\67\1\0\4\67\1\303\4\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\1\67"+
    "\1\304\3\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\7\67\1\0\2\67\1\0\11\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\4\67\1\305\13\0"+
    "\7\67\1\0\2\67\1\0\11\67\7\0\5\67\2\0"+
    "\4\67\4\0\2\67\4\0\4\67\1\306\13\0\7\67"+
    "\1\0\2\67\1\0\4\67\1\307\4\67\7\0\5\67"+
    "\2\0\4\67\4\0\2\67\4\0\5\67\13\0\7\67"+
    "\1\0\2\67\1\0\11\67\7\0\5\67\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\1\310\6\67\1\0"+
    "\2\67\1\0\1\311\10\67\7\0\5\67\2\0\4\67"+
    "\4\0\2\67\4\0\5\67\13\0\7\67\1\0\2\67"+
    "\1\0\1\312\10\67\7\0\5\67\2\0\4\67\4\0"+
    "\2\67\4\0\5\67\13\0\7\67\1\0\2\67\1\0"+
    "\11\67\7\0\5\67\2\0\4\67\4\0\2\67\4\0"+
    "\4\67\1\313\13\0\7\67\1\0\2\67\1\0\1\67"+
    "\1\314\7\67\7\0\5\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\11\67"+
    "\7\0\5\67\2\0\4\67\4\0\2\67\4\0\5\67"+
    "\13\0\2\67\1\315\4\67\1\0\2\67\1\0\11\67"+
    "\7\0\3\67\1\316\1\67\2\0\4\67\4\0\2\67"+
    "\4\0\5\67\13\0\7\67\1\0\2\67\1\0\11\67"+
    "\7\0\4\67\1\317\2\0\4\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67\1\0\2\67\1\0\11\67\7\0"+
    "\5\67\2\0\1\67\1\320\2\67\4\0\2\67\4\0"+
    "\5\67\13\0\7\67";

  private static int [] zzUnpackTrans() {
    int [] result = new int[9344];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\15\1\3\11\7\1\3\11\3\1\1\11"+
    "\7\1\1\11\1\1\1\11\1\1\5\11\22\1\2\11"+
    "\3\1\2\11\1\0\1\11\3\1\1\0\1\11\1\0"+
    "\1\11\1\0\1\11\1\0\6\1\1\0\1\11\1\0"+
    "\1\11\21\1\1\11\2\1\1\11\1\0\2\11\7\1"+
    "\1\11\1\0\17\1\1\11\4\1\1\0\20\1\1\11"+
    "\52\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[208];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 166) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 20: 
          { return parentDer;
          }
        case 78: break;
        case 21: 
          { return llaveDer;
          }
        case 79: break;
        case 10: 
          { return operadorModulo;
          }
        case 80: break;
        case 32: 
          { lexeme=yytext(); return Identificador;
          }
        case 81: break;
        case 22: 
          { return pesos;
          }
        case 82: break;
        case 26: 
          { return puntoDecimial;
          }
        case 83: break;
        case 55: 
          { return cadena;
          }
        case 84: break;
        case 70: 
          { return detener;
          }
        case 85: break;
        case 31: 
          { return gato;
          }
        case 86: break;
        case 3: 
          { return numero;
          }
        case 87: break;
        case 2: 
          { return guionBajo;
          }
        case 88: break;
        case 68: 
          { return arreglo;
          }
        case 89: break;
        case 11: 
          { return operadorPotencia;
          }
        case 90: break;
        case 73: 
          { return importar;
          }
        case 91: break;
        case 34: 
          { lexeme=yytext(); return Reservadas;
          }
        case 92: break;
        case 76: 
          { return funcionIntroducirDatos;
          }
        case 93: break;
        case 36: 
          { return incremento;
          }
        case 94: break;
        case 24: 
          { return corchetIzq;
          }
        case 95: break;
        case 17: 
          { return operadorNo;
          }
        case 96: break;
        case 4: 
          { /*Ignore*/
          }
        case 97: break;
        case 8: 
          { return operadorResta;
          }
        case 98: break;
        case 61: 
          { return funcionLeer;
          }
        case 99: break;
        case 48: 
          { return operadorPositivo;
          }
        case 100: break;
        case 14: 
          { return menorQue;
          }
        case 101: break;
        case 5: 
          { return letrasMin;
          }
        case 102: break;
        case 71: 
          { return cicloWhile;
          }
        case 103: break;
        case 54: 
          { return valorBooleano;
          }
        case 104: break;
        case 66: 
          { return cicloFor;
          }
        case 105: break;
        case 42: 
          { return inicioTexto;
          }
        case 106: break;
        case 67: 
          { return clase;
          }
        case 107: break;
        case 1: 
          { return ERROR;
          }
        case 108: break;
        case 19: 
          { return dosPuntos;
          }
        case 109: break;
        case 28: 
          { return comillaSimple;
          }
        case 110: break;
        case 77: 
          { return predeterminado;
          }
        case 111: break;
        case 51: 
          { return concatenar;
          }
        case 112: break;
        case 57: 
          { return condicionalElse;
          }
        case 113: break;
        case 39: 
          { return asignacion;
          }
        case 114: break;
        case 45: 
          { return saltoLinea;
          }
        case 115: break;
        case 64: 
          { return cicloDo;
          }
        case 116: break;
        case 43: 
          { return inicioComentarioMult;
          }
        case 117: break;
        case 37: 
          { return decremento;
          }
        case 118: break;
        case 13: 
          { return mayorQue;
          }
        case 119: break;
        case 65: 
          { return operadorRaiz;
          }
        case 120: break;
        case 35: 
          { return condicionalIf;
          }
        case 121: break;
        case 58: 
          { return funcionCase;
          }
        case 122: break;
        case 16: 
          { return operadorO;
          }
        case 123: break;
        case 44: 
          { return finalComentarioMult;
          }
        case 124: break;
        case 75: 
          { return constante;
          }
        case 125: break;
        case 25: 
          { return corchetDer;
          }
        case 126: break;
        case 59: 
          { return valorFlotante;
          }
        case 127: break;
        case 52: 
          { return comentarioLinea;
          }
        case 128: break;
        case 49: 
          { return operadorNegativo;
          }
        case 129: break;
        case 46: 
          { return puntoAcceso;
          }
        case 130: break;
        case 18: 
          { return parentIzq;
          }
        case 131: break;
        case 23: 
          { return llaveIzq;
          }
        case 132: break;
        case 40: 
          { return finalTexto;
          }
        case 133: break;
        case 33: 
          { lexeme=yytext(); return Numero;
          }
        case 134: break;
        case 50: 
          { return menorIgual;
          }
        case 135: break;
        case 27: 
          { return comillaDoble;
          }
        case 136: break;
        case 7: 
          { return operadorSuma;
          }
        case 137: break;
        case 12: 
          { return letrasMay;
          }
        case 138: break;
        case 47: 
          { return mayorIgual;
          }
        case 139: break;
        case 63: 
          { return funcionSalirCase;
          }
        case 140: break;
        case 69: 
          { return funcion;
          }
        case 141: break;
        case 29: 
          { return diagonalInvertido;
          }
        case 142: break;
        case 30: 
          { return signoAdmiracionAbre;
          }
        case 143: break;
        case 72: 
          { return variable;
          }
        case 144: break;
        case 74: 
          { return imprimir;
          }
        case 145: break;
        case 15: 
          { return operadorY;
          }
        case 146: break;
        case 38: 
          { return comparacionIgualdad;
          }
        case 147: break;
        case 41: 
          { return pi;
          }
        case 148: break;
        case 60: 
          { return caracter;
          }
        case 149: break;
        case 6: 
          { return operadorDivision;
          }
        case 150: break;
        case 9: 
          { return operadorMultiplicacion;
          }
        case 151: break;
        case 62: 
          { return funcionSwitch;
          }
        case 152: break;
        case 53: 
          { return valorEntero;
          }
        case 153: break;
        case 56: 
          { return finLinea;
          }
        case 154: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
